<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="8" hostname="HPLaptop" failures="8" tests="13" name="Test" time="72.099" errors="0" timestamp="2025-09-26T22:18:33 AEST">
  <testcase classname="api.tests.UserTests" name="createUserTest" time="3.3"/>
  <testcase classname="api.tests.UserTests" name="getUserTest" time="1.254"/>
  <testcase classname="api.tests.UserTests" name="updateUserTest" time="1.258">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.UserTests.updateUserTest(UserTests.java:78)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- updateUserTest -->
  <testcase classname="api.tests.UserTests" name="deleteUserTest" time="1.229">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.UserTests.deleteUserTest(UserTests.java:92)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deleteUserTest -->
  <testcase classname="api.tests.EmployeeTests" name="createEmployeeTest" time="1.487"/>
  <testcase classname="api.tests.EmployeeTests" name="getEmployeeTest" time="36.432">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at api.tests.EmployeeTests.getEmployeeTest(EmployeeTests.java:90)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- getEmployeeTest -->
  <testcase classname="api.tests.EmployeeTests" name="updateEmployeeTest" time="14.799">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at api.tests.EmployeeTests.updateEmployeeTest(EmployeeTests.java:125)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- updateEmployeeTest -->
  <testcase classname="api.tests.EmployeeTests" name="deleteUserTest" time="8.986"/>
  <testcase classname="api.tests.ObjectTests" name="getALLObjectsTest" time="0.892"/>
  <testcase classname="api.tests.ObjectDDTests" name="deleteObjectTest" time="0.215">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.ObjectDDTests.deleteObjectTest(ObjectDDTests.java:114)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deleteObjectTest -->
  <testcase classname="api.tests.ObjectDDTests" name="deleteObjectTest" time="0.427">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.ObjectDDTests.deleteObjectTest(ObjectDDTests.java:114)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deleteObjectTest -->
  <testcase classname="api.tests.ObjectDDTests" name="deleteObjectTest" time="0.198">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.ObjectDDTests.deleteObjectTest(ObjectDDTests.java:114)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deleteObjectTest -->
  <testcase classname="api.tests.ObjectDDTests" name="deleteObjectTest" time="0.222">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.ObjectDDTests.deleteObjectTest(ObjectDDTests.java:114)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deleteObjectTest -->
  <testcase classname="api.tests.ObjectTests" name="getObjectTest" time="0.0">
    <ignored/>
  </testcase> <!-- getObjectTest -->
  <testcase classname="api.tests.ObjectDDTests" name="getObjectTest" time="0.0">
    <ignored/>
  </testcase> <!-- getObjectTest -->
  <testcase classname="api.tests.ObjectDDTests" name="getALLObjectsTest" time="0.0">
    <ignored/>
  </testcase> <!-- getALLObjectsTest -->
  <testcase classname="api.tests.ObjectDDTests" name="createObjectTest" time="0.0">
    <ignored/>
  </testcase> <!-- createObjectTest -->
  <testcase classname="api.tests.ObjectTests" name="deleteObjectTest" time="0.0">
    <ignored/>
  </testcase> <!-- deleteObjectTest -->
  <testcase classname="api.tests.ObjectDDTests" name="createObjectTest2" time="0.0">
    <ignored/>
  </testcase> <!-- createObjectTest2 -->
  <testcase classname="api.tests.ObjectTests" name="updateObjectTest" time="0.0">
    <ignored/>
  </testcase> <!-- updateObjectTest -->
  <testcase classname="api.tests.ObjectTests" name="createObjectTest" time="0.0">
    <ignored/>
  </testcase> <!-- createObjectTest -->
</testsuite> <!-- Test -->
