<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="8" hostname="HPLaptop" failures="9" tests="13" name="Test" time="56.967" errors="0" timestamp="2025-09-27T23:43:50 AEST">
  <testcase classname="api.tests.UserTests" name="createUserTest" time="2.975"/>
  <testcase classname="api.tests.UserTests" name="getUserTest" time="1.276"/>
  <testcase classname="api.tests.UserTests" name="updateUserTest" time="1.245">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.UserTests.updateUserTest(UserTests.java:87)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- updateUserTest -->
  <testcase classname="api.tests.UserTests" name="deleteUserTest" time="1.34">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.UserTests.deleteUserTest(UserTests.java:101)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deleteUserTest -->
  <testcase classname="api.tests.EmployeeTests" name="createEmployeeTest" time="1.199"/>
  <testcase classname="api.tests.EmployeeTests" name="getEmployeeTest" time="15.474">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at api.tests.EmployeeTests.getEmployeeTest(EmployeeTests.java:101)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- getEmployeeTest -->
  <testcase classname="api.tests.EmployeeTests" name="updateEmployeeTest" time="14.826">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at api.tests.EmployeeTests.updateEmployeeTest(EmployeeTests.java:136)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- updateEmployeeTest -->
  <testcase classname="api.tests.EmployeeTests" name="deleteUserTest" time="14.658">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at api.tests.EmployeeTests.deleteUserTest(EmployeeTests.java:165)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deleteUserTest -->
  <testcase classname="api.tests.ObjectTests" name="getALLObjectsTest" time="0.87"/>
  <testcase classname="api.tests.ObjectDDTests" name="deleteObjectTest" time="0.259">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.ObjectDDTests.deleteObjectTest(ObjectDDTests.java:117)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deleteObjectTest -->
  <testcase classname="api.tests.ObjectDDTests" name="deleteObjectTest" time="0.299">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.ObjectDDTests.deleteObjectTest(ObjectDDTests.java:117)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deleteObjectTest -->
  <testcase classname="api.tests.ObjectDDTests" name="deleteObjectTest" time="0.305">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.ObjectDDTests.deleteObjectTest(ObjectDDTests.java:117)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deleteObjectTest -->
  <testcase classname="api.tests.ObjectDDTests" name="deleteObjectTest" time="0.405">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.ObjectDDTests.deleteObjectTest(ObjectDDTests.java:117)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deleteObjectTest -->
  <testcase classname="api.tests.ObjectDDTests" name="getALLObjectsTest" time="0.0">
    <ignored/>
  </testcase> <!-- getALLObjectsTest -->
  <testcase classname="api.tests.ObjectTests" name="getObjectTest" time="0.0">
    <ignored/>
  </testcase> <!-- getObjectTest -->
  <testcase classname="api.tests.ObjectTests" name="createObjectTest" time="0.0">
    <ignored/>
  </testcase> <!-- createObjectTest -->
  <testcase classname="api.tests.ObjectDDTests" name="getObjectTest" time="0.0">
    <ignored/>
  </testcase> <!-- getObjectTest -->
  <testcase classname="api.tests.ObjectTests" name="updateObjectTest" time="0.0">
    <ignored/>
  </testcase> <!-- updateObjectTest -->
  <testcase classname="api.tests.ObjectTests" name="deleteObjectTest" time="0.0">
    <ignored/>
  </testcase> <!-- deleteObjectTest -->
  <testcase classname="api.tests.ObjectDDTests" name="createObjectTest" time="0.0">
    <ignored/>
  </testcase> <!-- createObjectTest -->
  <testcase classname="api.tests.ObjectDDTests" name="createObjectTest2" time="0.0">
    <ignored/>
  </testcase> <!-- createObjectTest2 -->
</testsuite> <!-- Test -->
